### ISSUE TITLE
Do fizzbuzz with if, for

### ISSUE THREAD

**Issue by ulgoon** [kdt-be/fizzbuzz-team#1]
## 설명

i가 1부터 15까지 1씩 증가하면서,
i가 3의 배수라면 fizz를 출력
i가 5의 배수라면 buzz를 출력
i가 15의 배수라면 fizzbuzz를 출력
나머지 모든 경우는 i 를 그대로 출력.

## 할 일

- [x] Print fizz
- [x] Print buzz
- [x] Print fizzbuzz
- [ ] Wrap it up

## 참조

[https://en.wikipedia.org/wiki/Fizz_buzz](https://en.wikipedia.org/wiki/Fizz_buzz)

**Comment by kingwangzzang1234** [comment]
훌륭한 계획이군요 진행시키십시요
